<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?= $this->getChild('head')->toHtml() ?>
</head>
<body>
    <div id="header">
        <?= $this->getChild('header')->toHtml() ?>
    </div>
    <div id="left">
        <?= $this->getChild('left')->toHtml() ?>
    </div>
    <div id="content">
        <?= $this->getChild('content')->toHtml() ?>
    </div>
    <div id="footer">
        <?= $this->getChild('footer')->toHtml() ?>
    </div>
</body>
</html>
